### ISSUE TITLE
Warning when starting the server.

### ISSUE THREAD

**Issue by ShrkSoft** [PolskiStevek/EpicGuard#10]
Plugin it works but warning when starting the server.
No such file or directory?

Plugin Version : 3.8.3
Spigot 1.12.2

-Console log-
[WARNING] java.io.FileNotFoundException: plugins/EpicGuard/logs/EpicGuardLogs-24-2-2020.txt (No such file or directory)
[WARNING] at java.io.FileOutputStream.open0(Native Method)
[WARNING] at java.io.FileOutputStream.open(FileOutputStream.java:270)
[WARNING] at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[WARNING] at java.io.FileWriter.<init>(FileWriter.java:107)
[WARNING] at me.ishift.epicguard.universal.util.Logger.writeToFile(Logger.java:49)
[WARNING] at me.ishift.epicguard.universal.util.Logger.log(Logger.java:28)
[WARNING] at me.ishift.epicguard.universal.util.Logger.debug(Logger.java:13)
[WARNING] at me.ishift.epicguard.universal.cloud.CloudManager.connect(CloudManager.java:30)
[WARNING] at me.ishift.epicguard.bukkit.task.CloudTask.run(CloudTask.java:12)
[WARNING] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[WARNING] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[WARNING] at java.lang.Thread.run(Thread.java:748)
[WARNING] java.io.FileNotFoundException: plugins/EpicGuard/logs/EpicGuardLogs-24-2-2020.txt (No such file or directory)
[WARNING] at java.io.FileOutputStream.open0(Native Method)
[WARNING] at java.io.FileOutputStream.open(FileOutputStream.java:270)
[WARNING] at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[WARNING] at java.io.FileWriter.<init>(FileWriter.java:107)
[WARNING] at me.ishift.epicguard.universal.util.Logger.writeToFile(Logger.java:49)
[WARNING] at me.ishift.epicguard.universal.util.Logger.log(Logger.java:28)
[WARNING] at me.ishift.epicguard.universal.util.Logger.debug(Logger.java:13)
[WARNING] at me.ishift.epicguard.universal.cloud.CloudManager.connect(CloudManager.java:34)
[WARNING] at me.ishift.epicguard.bukkit.task.CloudTask.run(CloudTask.java:12)
[WARNING] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[WARNING] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[WARNING] at java.lang.Thread.run(Thread.java:748)
[WARNING] java.io.IOException: No such file or directory
[WARNING] at java.io.UnixFileSystem.createFileExclusively(Native Method)
[WARNING] at java.io.File.createNewFile(File.java:1012)
[WARNING] at me.ishift.epicguard.universal.util.Logger.create(Logger.java:38)
[WARNING] at me.ishift.epicguard.bukkit.task.CloudTask.run(CloudTask.java:15)
[WARNING] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[WARNING] at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[WARNING] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[WARNING] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[WARNING] at java.lang.Thread.run(Thread.java:748)

**Comment by PolskiStevek** [comment]
The issue should be fixed now (Latest dev build can be downloaded here: https://blaze-mc.pl/artifacts/).
Please inform me if the issue is fixed, so I can close this.

**Comment by ShrkSoft** [comment]
Thank you! Thanks for quick bug fixes!
