### ISSUE TITLE
PPS - Duration - Ping method

### ISSUE THREAD

**Issue by NikV2** [PolskiStevek/EpicGuard#13]
Greetings !

I noticed that in the latest update, The ping method has a few issues.
So for example the CPS check works perfectly, once a player joins after 1s it goes back to 0.
However the PPS will always update and never refresh.

Same goes for when an attack is happening. When the attack happens the server stays permanently whitelisted

**Comment by NikV2** [comment]
Also i think the automatic config updater has a few issues too, On each update if a configuration change was made it shakes up checks to different places (some of them) And at the end of the config it does not update the Version.

**Comment by PolskiStevek** [comment]
About config version at the end, this is what left from old ConfigUpdater, it is unused now. Can you create another issue about the configuration updater and provide more details? I'm going to fix the ping counter now.

**Comment by NikV2** [comment]
I'll run a few more tests and confirm it. Do i close this issue?

**Comment by PolskiStevek** [comment]
I will close it after I release commit which fixes this issue.
