### ISSUE TITLE
java.lang.NoClassDefFoundError with EpicGuardLite

### ISSUE THREAD

**Issue by breadbyte** [PolskiStevek/EpicGuard#15]
Error when starting up.
[Gist of crash log.](https://gist.github.com/breadbyte/5378107ae6608fad7e7ca9e1ef1943cb)
Server running Paper-121, Spigot 1.15.2.

**Comment by breadbyte** [comment]
Just tested, Regular EpicGuard works fine.

**Comment by PolskiStevek** [comment]
Investigated: Lite version does not include the storage library.
Status: Working on a fix...

**Comment by PolskiStevek** [comment]
I have updated EpicGuardLite.jar on the releases. It should be working now.

https://github.com/PolskiStevek/EpicGuard/releases/download/3.9.3/EpicGuardLite.jar

**Comment by breadbyte** [comment]
Tried the provided link, still getting the same issue.

**Comment by PolskiStevek** [comment]
Try now, created manually.

**Comment by breadbyte** [comment]
I see the filesize has updated. Works fine now, thank you!
