### ISSUE TITLE
Rozjebany epicguard

### ISSUE THREAD

**Issue by FasterSpeed** [PolskiStevek/EpicGuard#19]
**`Gdy mui przyjaciel botiing mai selwel wtedy epicguard  laguje baldzio mujk se3rwer wiuerc jewtem zmuszony wyjebaci ten lplugin. Napraw to jhebaniy debiluj fejk devew.`**

**Comment by PolskiStevek** [comment]
Issue has been found in the project and will be fixed in the latest update.
